version: '2.4'

services:
  nginx-php-fpm:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/usr/share/nginx/html/home
    networks:
      vpcbr:
        ipv4_address: 10.25.0.5
    restart: always

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.25.0.0/16
          gateway: 10.25.0.1
