version: '2'

services:
  nginx-php-fpm:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/usr/share/nginx/html/home
      - $PWD/docker/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/docker/nginx.conf:/etc/nginx/nginx.conf
      - $PWD:/usr/share/nginx/html/home
    ports:
      - "7979:80"
    networks:
      tankhahgardan_vpcbr:
        ipv4_address: 10.4.0.100
    restart: always

networks:
  tankhahgardan_vpcbr:
    external: true
#  vpcbr:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.25.0.0/16
#          gateway: 10.25.0.1
