version: '2.4'

services:
  nginx-php-fpm:
    image: "ahpiri/tankhah-production:4"
    #build:
    #  context: ./
    #  dockerfile: docker/Dockerfile
    volumes:
      - ./:/usr/share/nginx/html/home
      - $PWD/docker/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/docker/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/docker/supervisord.conf.new:/etc/supervisord.conf
    ports:
      - "7979:8185"
    networks:
      tankhahgardan_vpcbr:
        ipv4_address: 10.4.0.100
    restart: always

networks:
  tankhahgardan_vpcbr:
    external: true

