version: '2'

services:
  nginx-php-fpm:
    image: "ahpiri/nginx-php"
    volumes:
      - ./:/usr/share/nginx/html/home
      - $PWD/docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8185:8185"
    networks:
      default:
        ipv4_address: 10.4.0.20
    restart: always


networks:
  default:
    external:
      name: tankhahgardan_vpcbr



