version: '2'

services:
  nginx-php-fpm:
    image: registry.domusgroup.ir/upstream/php-octane:php81
    container_name: tankhahgardan_panel
    volumes:
      - ./:/usr/share/nginx/html/home
      - $PWD/docker/supervisord.conf:/etc/supervisord.conf
      - $PWD/docker/default.conf:/etc/nginx/conf.d/default.conf
      - $PWD/docker/service.start:/usr/local/bin/service.start
        #      - $PWD/docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
    healthcheck:
      test: curl --fail -s http://localhost:8185/_ping || exit 1
    environment:
     - TZ=Asia/Tehran
    restart: always


networks:
  default:
    external:
      name: tankhahgardan_default



