version: '2'

services:
  nginx-php-fpm:
    image: registry.domusgroup.ir/upstream/php-octane:php81
    container_name: tankhahgardan_panel_backend
    volumes:
      - ./:/usr/share/nginx/html/home
        #      - $PWD/docker/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
    restart: always


networks:
  default:
    external:
      name: tankhahgardan_default



